stages:
  - build
  - clear
  - push
  - deploy

build-dev:
  image: docker:latest
  stage: build
  script:
    - tar -czvf tmp.tgz *
    - docker build -t samfashion-manerger .
  only:
    - deploy-dev

clear-dev:
  stage: clear
  only:
    - deploy-dev
  script:
    - docker rmi www.mscreativestyle.com/samfashion/samfashion-manerger
  allow_failure: true

push-dev:
  stage: push
  only:
    - deploy-dev
  script:
    - docker tag samfashion-manerger localhost:5000/samfashion/samfashion-manerger
    - docker push localhost:5000/samfashion/samfashion-manerger

  after_script:
    - docker images


deploy-dev:
  image: ubuntu:latest
  stage: deploy
  only:
    - deploy-dev
  script:
    - apt-get update
    - apt-get install sshpass
   

